#Service Mesh
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: stable
  installApprovalPlan: Automatic

