## ElasticSearch Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators 
spec:
  name: elasticsearch-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  channel: preview
  installApprovalPlan: Automatic
## Jaeger Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators 
spec:
  name: elasticsearch-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace

## Kiali  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm 
  namespace: openshift-operators 
spec:
  name: kiali-ossm 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  channel: stable
  installApprovalPlan: Automatic

##Service Mesh
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators 
spec:
  name: servicemeshoperator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  channel: '1.0'
  installApprovalPlan: Automatic
